# Generated by Django 3.2 on 2022-08-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deudor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='data_de_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
